site_name: Event Framework
repo_url: https://github.com/caverac/event-framework
repo_name: caverac/event-framework
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
    - content.action.view
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: "Switch to light mode"
edit_uri: edit/main/docs/

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_signature: true
  - bibtex:
      bib_file: docs/refs.bib
      csl_file: docs/apa.csl
      enable_inline_citations: false

markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

nav:
  - Home: index.md
  - Building the Framework:
      - Part I: building-the-framework-1.md
      - Part II: building-the-framework-2.md
  - Domain Driven Design: ddd.md
  - Existing Solutions: existing-solutions.md
  - Glossary: glossary.md

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
